### ISSUE TITLE
spack install lammps fails

### ISSUE THREAD

**Issue by PabloRodenas** [fujitsu/oss-patches-for-a64fx#1]
I am testing spack for installing different software on a aarch64 machine. My spack config files are based on the Spack/README.md. First, I tried to use spack with cross-compilation on login's node but it fails on the tests part of the very first dependency. So now I am executing spack directly on a compute node.

Trying to install LAMMPS, spack fails on the kim-api dependency when applying the fujitsu_add_link_flags.patch:

> spack install lammps @20190807 %fj
> ...
> ==> Installing kim-api-2.2.1-uyd3ce3m7kldqucdnflqkbkfjm7cytpv
> ==> No binary for kim-api-2.2.1-uyd3ce3m7kldqucdnflqkbkfjm7cytpv found: installing from source
> ==> Using cached archive: 
> 
> /apps/SPACK/spack/var/spack/cache/_source-cache/archive/1d/1d5a12928f7e885ebe74759222091e48a7e46f77e98d9147e26638c955efbc8e.txz
> 
> 2 out of 2 hunks FAILED -- saving rejects to file cmake/Modules/DefaultCompilerFlags.cmake.rej
> ==> Patch /apps/SPACK/spack/var/spack/repos/builtin/packages/kim-api/fujitsu_add_link_flags.patch failed.
> ==> Error: ProcessError: Command exited with status 1:
>     '/usr/bin/patch' '-s' '-p' '1' '-i' '/apps/SPACK/spack/var/spack/repos/builtin/packages/kim-api/fujitsu_add_link_flags.patch' '-d' '.'
> ==> Warning: Skipping build of lammps-20190807-v7f3r7w7zqifijjqwkfz6jhjktasm7lw since kim-api-2.2.1-uyd3ce3m7kldqucdnflqkbkfjm7cytpv failed
> ==> Error: lammps-20190807-v7f3r7w7zqifijjqwkfz6jhjktasm7lw: Package was not installed
> ==> Error: Installation request failed.  Refer to reported errors for failing package(s).
> 

I've interactively tested the command and seems that the lines specified on the fujitsu_add_link_flags.patch are totally different of the content of the cmake/Modules/DefaultCompilerFlags.cmake.

If you can help me to compile LAMMPS on aarch64 would be really helpful.

Thanks in advance.

**Comment by m-shunji** [comment]
The fujitsu_add_link_flags.patch seems to be incompatible with the newest version of kim-api.
Could you try specifying older version by the following command ?
`spack install lammps @20190807 ^kim-api@2.1.3 %fj`

We didn't encounter this problem because kim-api was added as lammps dependencies only recently.
We will update information after confirming this workaround works well.

**Comment by BSC-Support-Team** [comment]
I got have LAMMPS installed! I confirm that your suggestion worked perfectly. 
Many thanks for your answer.

**Comment by PabloRodenas** [comment]
I got have LAMMPS installed! I confirm that your suggestion worked perfectly.
Many thanks for your answer.
